import React,{useEffect,useState}from'react';
import{FileText,Loader2,PackageCheck,Printer,RefreshCcw}from'lucide-react';
import{fetchUnifiedInventory,type CommerceBusinessSettings,type UnifiedInvoiceRow,type UnifiedOrderRow,type UnifiedProductLot,type UnifiedShipmentRow}from'../services/commerceInventory';
import{openCommerceDocument,sellerIsInvoiceReady}from'../services/commerceDocuments';

const eur=(n:number)=>new Intl.NumberFormat('nb-NO',{style:'currency',currency:'EUR'}).format(n||0);

const DonaAnnaOrderDocumentsOliviaView:React.FC=()=>{
 const[orders,setOrders]=useState<UnifiedOrderRow[]>([]),[lots,setLots]=useState<UnifiedProductLot[]>([]),[invoices,setInvoices]=useState<UnifiedInvoiceRow[]>([]),[shipments,setShipments]=useState<UnifiedShipmentRow[]>([]),[settings,setSettings]=useState<CommerceBusinessSettings|null>(null);
 const[loading,setLoading]=useState(true),[error,setError]=useState('');
 const load=async()=>{setLoading(true);setError('');try{const d=await fetchUnifiedInventory();setOrders(d.orders.filter(o=>o.status.toLowerCase()!=='test'&&o.total_amount>0));setLots(d.lots);setInvoices(d.invoices);setShipments(d.shipments);setSettings(d.businessSettings);}catch(e:any){setError(e?.message||'Kunne ikke hente ordredokumenter.');}finally{setLoading(false);}};
 useEffect(()=>{load();},[]);
 return <div className="space-y-6">
  <div className="flex flex-col gap-3 md:flex-row md:items-end md:justify-between"><div><p className="text-xs font-bold uppercase tracking-[0.24em] text-amber-300">Doña Anna · dokumenter</p><h2 className="mt-2 text-3xl font-black text-white">Ordrebekreftelser, pakksedler og faktura</h2><p className="mt-2 max-w-3xl text-sm text-slate-400">Samme ordredata som B2B og Salg og lager. Ingen separat ordreliste eller demo-ordre brukes her.</p></div><button onClick={load} className="rounded-xl border border-white/10 bg-white/5 px-4 py-2.5 text-xs font-bold text-white flex items-center gap-2"><RefreshCcw size={15}/>Oppdater</button></div>
  {!sellerIsInvoiceReady(settings)&&<div className="rounded-2xl border border-amber-300/20 bg-amber-300/10 p-4 text-sm text-amber-100"><strong>Faktura er fortsatt i sikker utkastmodus.</strong> Fyll inn juridisk navn, NIF/CIF og adresse under Salg og lager → Fakturainnstillinger før faktura sendes til kunde.</div>}
  {error&&<div className="rounded-2xl border border-red-500/30 bg-red-500/10 p-4 text-sm text-red-100">{error}</div>}
  {loading?<div className="flex items-center gap-2 text-slate-400"><Loader2 className="animate-spin" size={18}/>Henter reelle ordre…</div>:orders.length===0?<div className="rounded-3xl border border-white/10 bg-white/[0.03] p-8 text-center"><FileText className="mx-auto text-slate-600" size={36}/><p className="mt-3 font-bold text-white">Ingen reelle ordre ennå</p><p className="mt-1 text-sm text-slate-500">De to testordrene på €0 holdes med vilje utenfor dokumenter, lager og økonomi.</p></div>:
  <div className="grid gap-4">{orders.map(order=>{const invoice=invoices.find(i=>i.order_id===order.id),shipment=shipments.find(s=>s.order_id===order.id);return <article key={order.id} className="rounded-3xl border border-white/10 bg-white/[0.03] p-5"><div className="flex flex-col gap-3 md:flex-row md:items-start md:justify-between"><div><p className="text-lg font-black text-white">{order.order_number}</p><p className="text-xs text-slate-500 mt-1">{order.customer?.company||order.customer_name||order.customer?.contact_name||'Kunde'} · {order.status} · {order.items.length} ordrelinje(r)</p></div><strong className="text-xl text-white">{eur(order.total_amount)}</strong></div>
   <div className="mt-4 space-y-2">{order.items.map(item=>{const lot=item.lot_id?lots.find(l=>l.id===item.lot_id):undefined;return <div key={item.id} className="flex items-center justify-between gap-3 rounded-xl bg-black/20 px-3 py-2 text-sm"><span className="text-slate-300">{item.quantity} × {item.name}</span><span className={lot?'text-green-400':'text-amber-300'}>{lot?lot.lot_code:'Lot ikke koblet'}</span></div>})}</div>
   <div className="mt-4 flex flex-wrap gap-2"><button onClick={()=>openCommerceDocument({type:'order_confirmation',order,invoice,shipment,lots,settings})} className="rounded-xl bg-white/10 px-3 py-2 text-xs font-bold text-white flex items-center gap-1"><Printer size={14}/>Ordrebekreftelse</button><button onClick={()=>openCommerceDocument({type:'packing_slip',order,invoice,shipment,lots,settings})} className="rounded-xl bg-white/10 px-3 py-2 text-xs font-bold text-white flex items-center gap-1"><PackageCheck size={14}/>Pakkseddel</button>{invoice&&<button onClick={()=>openCommerceDocument({type:'invoice',order,invoice,shipment,lots,settings})} className="rounded-xl bg-blue-500/15 px-3 py-2 text-xs font-bold text-blue-300 flex items-center gap-1"><Printer size={14}/>{sellerIsInvoiceReady(settings)?invoice.invoice_number+' PDF':invoice.invoice_number+' utkast'}</button>}</div>
  </article>})}</div>}
 </div>;
};
export default DonaAnnaOrderDocumentsOliviaView;
